package ch.heigvd.iict.dma.exercices_nfc.models

import android.net.Uri
import android.nfc.NdefRecord
import android.util.Log
import java.util.Arrays

interface MyNdefMessage {
    var id : Long

    fun copy() : MyNdefMessage

    companion object {
        var nextId = 0L

        private val TAG = MyNdefMessage::class.java.simpleName

        fun parseRecord(record : NdefRecord) : MyNdefMessage {
            if(record.tnf != NdefRecord.TNF_WELL_KNOWN) {
                Log.d(TAG, "Can only parse TNF_WELL_KNOWN records")
                throw java.lang.IllegalArgumentException("Can only parse TNF_WELL_KNOWN records")
            }
            if(Arrays.equals(record.type, NdefRecord.RTD_TEXT)) {
                val payload = record.payload
                // 0x80 = [10000000] - most significant bit - bit 7
                val textEncoding = if ((payload[0].toInt() and 0x80) == 0) Charsets.UTF_8 else Charsets.UTF_16
                // 0x3F = [00111111] - bits 5-0
                val languageCodeLength = payload[0].toInt() and 0x3F
                val languageCode = String(payload, 1, languageCodeLength, Charsets.US_ASCII)
                val value = String(payload, 1 + languageCodeLength, payload.size - (1+languageCodeLength), textEncoding)
                return MyTextNdefMessage(languageCode, value)
            }
            else if(Arrays.equals(record.type, NdefRecord.RTD_URI)) {
                //TODO decoder le contenu NDEF RTD_URI
                return MyUriNdefMessage(Uri.parse("http://to.do"))
            }
            throw java.lang.IllegalArgumentException("Unknown RTD type <${byteArrayOf(*record.type).toHex()}>")
        }
    }
}

fun ByteArray.toHex(): String = joinToString(separator = "") { eachByte -> "%02x".format(eachByte) }

class MyUriNdefMessage(val uri: Uri) : MyNdefMessage  {
    override var id = MyNdefMessage.nextId++

    override fun copy() = MyUriNdefMessage(uri)

    override fun equals(other: Any?): Boolean { /* autogenerated by ide */
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as MyUriNdefMessage

        if (uri != other.uri) return false
        if (id != other.id) return false

        return true
    }

    override fun hashCode(): Int { /* autogenerated by ide */
        var result = uri.hashCode()
        result = 31 * result + id.hashCode()
        return result
    }
}

class MyTextNdefMessage(val languageCode: String, val value: String) : MyNdefMessage {
    override var id = MyNdefMessage.nextId++

    override fun copy() = MyTextNdefMessage(languageCode, value)

    override fun equals(other: Any?): Boolean { /* autogenerated by ide */
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as MyTextNdefMessage

        if (languageCode != other.languageCode) return false
        if (value != other.value) return false
        if (id != other.id) return false

        return true
    }

    override fun hashCode(): Int { /* autogenerated by ide */
        var result = languageCode.hashCode()
        result = 31 * result + value.hashCode()
        result = 31 * result + id.hashCode()
        return result
    }

}
